#
# Python 3 Titus travis.yml config file
#
# YAML Validator:   http://lint.travis-ci.org/
#

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  directories:
    - $HOME/cached

before_install:
  - cd $HOME/cached
  - |
    if [ ! -f pfa-tests.json ]
    then
      wget http://github.com/datamininggroup/pfa/releases/download/0.8.1/pfa-tests.json
    fi 
  - head pfa-tests.json
  - cd $HOME/build/animator/pfa
  
# command to install dependencies
install:
  - pip install numpy
  - pip install titus2
  
# command to run tests
script:
  - python conformance-tests/runTestTitus.py $HOME/cached/pfa-tests.json
  
# Push the results back to codecov
# after_success:
#   - codecov
notifications:
  email: false
