#
# Python 3 Titus travis.yml config file
#
# YAML Validator:   http://lint.travis-ci.org/
#

language: python
python:
  - "3.7"


cache:
  directories:
    - $HOME/cached

before_install:
  - cd $HOME/cached
  - pwd
  - ls
  - [ ! -f pfa-tests.json ] && wget http://github.com/datamininggroup/pfa/releases/download/0.8.1/pfa-tests.json
  - ls  
  - head pfa-tests.json
  - cd $HOME/build/animator/pfa
  
# command to install dependencies
install:
  - pip install git+https://github.com/animator/python3-titus.git
  
# command to run tests
script:
  - pwd
  - ls
  - python conformance-tests/runTestTitus.py $HOME/cached/pfa-tests.json
  
# Push the results back to codecov
# after_success:
#   - codecov
notifications:
  email: false
